### ISSUE TITLE
Replace creating local cert manually with local-ssl-proxy

### ISSUE THREAD

**Issue by deiga** [KinToday/kin-web-client#13]
Hey,

Creating certs manually is always a bit of a hassle (even though you listed a good step by step list).
Would make sense to instead use [local-ssl-proxy](https://github.com/cameronhunter/local-ssl-proxy)?

**Comment by zowesiouff** [comment]
I would personally stay away from it, for multiple reasons:

1- they embed a cert / private key in their repository: Even though they mention that you can comfortably ignore your browser's security warning because it's a self-signed certificate, after a while, you will want to save an exception. It's imho a security hazard if you don't control the private key (even though the cert's CN is `localhost` which probably reduces the risk on this)

2- you will still have some setup to make OAuth works (dynDNS, noip ... ). Even though the hosts trick is ... a trick, at least it's constrained on your host and doesn't depend on an external service.

3- cert uses sha1, which really should be upgraded to sha256 (at least) and given the cert's massive expiration date (10 years, ending in 2023), this is another security hazard.

I'm really no security expert and I guess rolling your own commands in a doc ilke what Kin's doing right now probably has a few flaws as well :D

**Comment by deiga** [comment]
Number 2 is no problem IMHO as you can just say `local-ssl-proxy -n dev.kin.today`

With the rest I agree or see your point :)

**Comment by zowesiouff** [comment]
You're completely right about 2- not being a probem :) 

Closing this for now.
